In [29]:
import pandas as pd
import array
import numpy as np

In [30]:
data=pd.read_csv("Restaurant_Reviews.tsv",sep="\t")#remove tabs in each line

In [31]:
print(data)

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]


In [32]:
print(data["Liked"].value_counts())#to see how many times each class appeared

1    500
0    500
Name: Liked, dtype: int64


In [33]:
data["Review letter count"]=data["Review"].apply(len)#just to know number of letters the line contain
print(data)

                                                Review  Liked  \
0                             Wow... Loved this place.      1   
1                                   Crust is not good.      0   
2            Not tasty and the texture was just nasty.      0   
3    Stopped by during the late May bank holiday of...      1   
4    The selection on the menu was great and so wer...      1   
..                                                 ...    ...   
995  I think food should have flavor and texture an...      0   
996                           Appetite instantly gone.      0   
997  Overall I was not impressed and would not go b...      0   
998  The whole experience was underwhelming, and I ...      0   
999  Then, as if I hadn't wasted enough of my life ...      0   

     Review letter count  
0                     24  
1                     18  
2                     41  
3                     87  
4                     59  
..                   ...  
995                   66  
996

In [34]:
x=data["Review"]
print(x)

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...                        
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: Review, Length: 1000, dtype: object


In [35]:
import nltk


In [36]:
from nltk.corpus import *
from nltk.tokenize import *
import re

#--->just for test---->

In [37]:
#s=data['Review'][0]
#s=re.sub("[^a-zA-Z]"," ",s)
#s=s.lower()
#s=word_tokenize(s)
#print(s)
#temp=[]
#for word in s:
    #if word not in stopwords.words("english"):
       # temp.append(word)
#print(temp) 
#s=' '.join(temp)       
from sklearn.feature_extraction.text import CountVectorizer
#cv=CountVectorizer()
#cv.fit_transform(word_tokenize(s)).toarray()    

Preprocessing(ConvertToLower,remove Punc and stopwords)

In [38]:
from nltk.stem import WordNetLemmatizer
lemma=WordNetLemmatizer()
s=''
corpus=[]
for i in range (len(data)):
    s=re.sub("[^a-zA-Z]"," ",data["Review"][i])
    s=word_tokenize(s)
    s=[word.lower() for word in s if word not in stopwords.words("english")]
    s=' '.join(s)
    s=lemma.lemmatize(s)
    print(s)
    corpus.append(s)     
print(corpus)    

wow loved place
crust good
not tasty texture nasty
stopped late may bank holiday rick steve recommendation loved
the selection menu great prices
now i getting angry i want damn pho
honeslty taste that fresh
the potatoes like rubber could tell made ahead time kept warmer
the fries great
a great touch
service prompt
would go back
the cashier care ever i say still ended wayyy overpriced
i tried cape cod ravoli chicken cranberry mmmm
i disgusted i pretty sure human hair
i shocked signs indicate cash
highly recommended
waitress little slow service
this place worth time let alone vegas
like
the burrittos blah
the food amazing
service also cute
i could care less the interior beautiful
so performed
that right red velvet cake ohhh stuff good
they never brought salad asked
this hole wall great mexican street tacos friendly staff
took hour get food tables restaurant food luke warm our sever running around like totally overwhelmed
the worst salmon sashimi
also combos like burger fries beer decent 

Feature Extraction

In [39]:
cv=CountVectorizer()
cv.fit(corpus)#convert each word into representaion like-->(eat)-->(1 0 0) and Learn vocab
#joblib.dump(cv, 'CV.joblib')
X=cv.transform(corpus).toarray()#convert representaion into vector
print(X)
cv.vocabulary_#positionبتظهرلي كل كلمة و جنبها   

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


{'wow': 1931,
 'loved': 991,
 'place': 1267,
 'crust': 394,
 'good': 723,
 'not': 1136,
 'tasty': 1695,
 'texture': 1708,
 'nasty': 1110,
 'stopped': 1634,
 'late': 936,
 'may': 1032,
 'bank': 112,
 'holiday': 817,
 'rick': 1424,
 'steve': 1626,
 'recommendation': 1380,
 'the': 1713,
 'selection': 1496,
 'menu': 1054,
 'great': 737,
 'prices': 1311,
 'now': 1139,
 'getting': 705,
 'angry': 40,
 'want': 1862,
 'damn': 405,
 'pho': 1253,
 'honeslty': 820,
 'taste': 1691,
 'that': 1711,
 'fresh': 673,
 'potatoes': 1299,
 'like': 962,
 'rubber': 1441,
 'could': 362,
 'tell': 1700,
 'made': 1006,
 'ahead': 19,
 'time': 1741,
 'kept': 914,
 'warmer': 1866,
 'fries': 679,
 'touch': 1764,
 'service': 1509,
 'prompt': 1323,
 'would': 1929,
 'go': 716,
 'back': 103,
 'cashier': 261,
 'care': 252,
 'ever': 567,
 'say': 1474,
 'still': 1628,
 'ended': 547,
 'wayyy': 1879,
 'overpriced': 1193,
 'tried': 1777,
 'cape': 248,
 'cod': 315,
 'ravoli': 1363,
 'chicken': 287,
 'cranberry': 379,
 'mmmm': 1

In [40]:
labels=cv.get_feature_names_out()#to get Vocabulary OR word without position
print(labels)
#pd.DataFrame(data=X,columns=cv.get_feature_names_out())#to set Vocab and repetition of words 


['absolute' 'absolutely' 'absolutley' ... 'yum' 'yummy' 'zero']


In [41]:
y=data["Liked"]
print(y)

0      1
1      0
2      0
3      1
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Liked, Length: 1000, dtype: int64


Train The Model

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.20,random_state=40)

In [44]:
from sklearn.naive_bayes import MultinomialNB
##-->acuuracy=0.81-->>>good
#from sklearn.linear_model import LogisticRegression
#model = LogisticRegression()

#-->accuracy=0.66-->so bad 
#from sklearn.neighbors import KNeighborsClassifier
#model=KNeighborsClassifier(n_neighbors=23)

model=MultinomialNB()
model.fit(X_train,Y_train)

MultinomialNB()

In [45]:
y_pred=model.predict(X_test)

In [46]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,y_pred))

0.81


In [47]:
import joblib
joblib.dump(model, 'sentmachine.joblib')

['sentmachine.joblib']